alembic==1.11.1
asgiref==3.7.2
Babel==2.12.1
beautifulsoup4==4.12.2
blinker==1.4
branca==0.6.0
cachelib==0.9.0
certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi
cffi==1.15.1
chardet==3.0.4
charset-normalizer==3.3.2
CIRpy==1.0.2
click==8.1.3
colorama==0.4.6
cryptography==41.0.5
cycler==0.11.0
Django==3.2.21
dnspython==2.3.0
docx2pdf==0.1.8
docxcompose==1.4.0
docxtpl==0.16.7
email-validator==2.0.0.post2
et-xmlfile==1.1.0
Flask==2.2.5
Flask-Caching==2.0.2
Flask-Dance==0.14.0
Flask-DebugToolbar==0.13.1
Flask-Login==0.6.2
Flask-Mail==0.9.1
Flask-Migrate==4.0.4
Flask-OAuth==0.12
Flask-OAuthlib==0.9.4
Flask-Session==0.5.0
Flask-SQLAlchemy==3.0.5
Flask-WTF==1.1.1
folium==0.14.0
fonttools==4.38.0
geographiclib==2.0
geopy==2.4.1
git-filter-repo==2.38.0
greenlet==2.0.2
httplib2==0.11.3
idna==2.6
image==1.5.33
importlib-metadata==6.6.0
importlib-resources==5.12.0
itsdangerous==2.1.2
Jinja2==3.0.3
kiwisolver==1.4.5
lazy==1.3
lxml==4.9.3
Mako==1.0.7
MarkupSafe==2.1.2
matplotlib==3.5.3
numpy==1.21.6
oauth2==1.9.0.post1
oauthlib==2.0.7
openpyxl==3.1.2
packaging==23.2
pandas==1.3.5
Pillow==9.5.0
plotly==5.18.0
plum-dispatch==1.7.4
PubChemPy==1.0.4
pycparser==2.21
PyMuPDF==1.22.5
pyOpenSSL==23.3.0
pyparsing==3.1.1
pypdf==4.2.0
pypng==0.20220715.0
PyQRCode==1.2.1
python-dateutil==2.8.2
python-decouple==3.8
python-docx==0.8.11
python-dotenv==0.21.1
python-editor==1.0.3
pytz==2023.3
pywin32==306
pyzbar==0.1.9
qrcode==7.4.2
qrtools==0.0.2
requests==2.31.0
requests-oauthlib==0.8.0
six==1.11.0
soupsieve==2.4.1
SQLAlchemy==2.0.15
SQLAlchemy-Utils==0.33.2
sqlparse==0.4.4
tenacity==8.2.3
tqdm==4.66.1
typing_extensions==4.6.2
unicodeit==0.7.5
Unidecode==1.3.6
urllib3==2.0.7
URLObject==2.4.3
waitress==2.1.2
Werkzeug==2.2.3
wincertstore==0.2
WTForms==2.3.1
xlrd==2.0.1
zipp==3.15.0
